version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm ci
      - run: npm test
      - run: npm run build
  store_test_results:
    path: test-results
  store_artifacts:
    path: coverage
